-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnOoPwksflHSm6Hsf
fDHNYanlin4RlV9rim2NyEaDarKgCgYIKoZIzj0DAQehRANCAASXaKiSt74qQPfW
wv5TH4feYW+L5kLsGjvM2ofY08FQMuHwkjQGGa84vy1czdP9iXOJKgRObjwlEgfq
p59RGKQT
-----END PRIVATE KEY-----